apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
spec:
  capacity:
    storage: 100Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: spinningrust
  mountOptions:
    - hard
    - nfsvers=3
  nfs: 
    path: /mnt/Z2/k8s 
    server: 192.168.32.32 
    readOnly: false
