apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloudStorage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage:100Gi
  storageClassName: spinningrust
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
